- pyproject.toml
App Release v0.0.3 - fix bug with large prompts + smaller bugs
> release: bump version to v0.0.3

- source/docq/config.py
- source/docq/support/llm.py
Adding document metadata during (re)indexing to support https://github.com/docqai/docq/pull/36
cc @osala-eng
> Use document metadata during (re)indexing

- source/docq/access_control/main.py
- source/docq/manage_groups.py
- source/docq/manage_spaces.py
- source/docq/manage_users.py
- web/admin_groups.py
- web/admin_users.py
- web/index.py
- web/utils/formatters.py
- web/utils/handlers.py
- web/utils/layout.py
Adding end-to-end support for controlling access to shared spaces. 
In the process also adding (user) groups support, plus some UI reconditioning. 
#19 is related pending group implementation. 
> Add support for shared space permissions

- source/docq/run_queries.py
Fixes retrieve last_n history to retrieve the latest 10 history
> fix: Modify retrieve last_n to retrieve the latest 10 history

- source/docq/run_queries.py
- source/docq/support/store.py
- web/utils/constants.py
- web/utils/handlers.py
- web/utils/layout.py
Implements #64 
The approach taken implements the foundation for supporting multiple threads in the UI. 
In another PR we can add UI to:
- UX to switch between threads
- functionality to set thread `topic` text based on the initial prompt.
- deleting a thread
> feat: rest history with new chat - chat history threads

- source/docq/domain.py
- source/docq/manage_documents.py
- source/docq/manage_organisations.py
- source/docq/manage_orgs.py
- source/docq/manage_settings.py
- source/docq/manage_space_groups.py
- source/docq/manage_spaces.py
- source/docq/manage_user_groups.py
- source/docq/manage_users.py
- source/docq/run_queries.py
- source/docq/setup.py
- source/docq/support/store.py
- tests/docq/data_source/manual_upload_test.py
- tests/docq/domain_test.py
- tests/docq/manage_spaces_test.py
- tests/docq/support/store_test.py
- web/admin_orgs.py
- web/admin_users.py
- web/index.py
- web/personal_docs.py
- web/utils/constants.py
- web/utils/handlers.py
- web/utils/layout.py
- web/utils/sessions.py
Adds the concept of Orgs
See this comment for details on the implementation
Note1: I decided not to go down the path of creating a default org for a user for now. I think that's warranted when self service sign up is implemented. Doing this would also require reworking the personal ask feature IMO otherwise it would be confusing. This MVP version assumes we'll (super admins) will setup orgs and create the initial user(s).
WARNING! this is a breaking share and the database layer. Database migration isn't implemented.
Implements #44 
Org switch appears on home and users only for now:
**Test …
> Feat!: multi tenancy by adding `orgs` as a concept

- pyproject.toml
- source/docq/run_queries.py
- source/docq/support/llm.py
- Bump version 0.0.3 -> 0.1.0 for release
- Fix: Ask Your Docs not returning sources issue
> release: bump version from 0.0.3 -> 0.1.0 in project TOML file for release

- infra/azure/arm/appservice.json
- infra/azure/arm/deploy.sh
text-davinci is deprecated now and breaks the Arm template.
`gpt-35-turbo` is the recommended for chat and generation.
adding `text-embedding-ada-002` instead of davinci for embedding as per recommendation
Infra deploys successfully. Application integration not tested as Auzre OpenAI support isn't coded yet.
Please describe the …
> Infra: update Azure OpenAI models

- .github/workflows/codeql.yml
Stop CodeQL analysis from running on PRs and Push. It takes way too long, 10s on mins. Only run on a schedule, daily at 2:25AM
> Build: switch to checked-in CodeQL config for customisation

- source/docq/manage_organisations.py
- source/docq/manage_settings.py
- source/docq/manage_spaces.py
- source/docq/manage_users.py
- web/admin_users.py
- web/utils/constants.py
- web/utils/error_ui.py
- web/utils/handlers.py
- web/utils/layout.py
- feat: create a personal org for new users.
- refactor!: default selected org state is now set to the users personal org when they login
- feat (UI): add pretty error handling system
- fix: various to create user and create+update org
- refactor!: admin menus shows based on org_admin rather than super_admin role.
Implements first part for #102
> Feat: create personal org for new users

- pyproject.toml
- source/docq/support/llm.py
- source/docq/support/store.py
> add: only do download if the model folder doesn't exist

- pyproject.toml
- source/docq/domain.py
- source/docq/run_queries.py
- web/utils/handlers.py
- web/utils/layout.py
Fixes general chat feature crashing. A code path that should run for general chat was being triggered due to a missing feature check.
> fix(general chat): throwing error due to missing feature check

- pyproject.toml
- source/docq/__init__.py
- web/index.py
- web/utils/layout.py
Fixes general chat feature crashing. A code path that should run for general chat was being triggered due to a missing feature check.
> feat:add version info to `about` menu topright

- Dockerfile
- pyproject.toml
- Secrets and none secret values
- At app startup time inside the container Infisical CLI injects values into the app.
> infra(container): pull ENVs from Infisical

- pyproject.toml
- source/docq/model_selection/main.py
- web/utils/layout.py
> feat: add lic and citation to model info in settings

- .gitignore
- docs/developer-guide/getting-started.md
- misc/docker.env.template
- misc/secrets.toml.template
- poetry.lock
- pyproject.toml
- source/docq/data_source/main.py
- source/docq/data_source/manual_upload.py
- source/docq/manage_spaces.py
- source/docq/manage_users.py
- source/docq/setup.py
- source/docq/support/llamaindex_otel_callbackhandler.py
- source/docq/support/llm.py
- source/docq/support/node_parsers.py
- web/utils/handlers.py
> chore(observability): Add OpenTelemetry instrumentation with Honeycomb exporter

- web/utils/layout.py
> fix: shared space selector

- web/utils/layout.py
Fix space selector not rendering correctly
Fixes/Implements #154 
> fix: Fix space selector not rendering properly.

- misc/pytest.env.template
- pyproject.toml
- source/docq/run_queries.py
- tests/integration/backend_integration_test.py
- tests/utilities.py
Fix broken integration tests.
Fixes/Implements #159 
> test: fix integration tests

- poetry.lock
- pyproject.toml
- source/docq/extensions.py
- source/docq/support/llamaindex_otel_callbackhandler.py
- source/docq/support/llm.py
> refactor: switch to LiteLLM

- poetry.lock
- pyproject.toml
- web/utils/layout.py
Update streamlit to the latest version.
implements #165
> chore: update streamlit to latest version (v1.24.0 -> v1.28.2)

- web/utils/layout.py
Fix UI bugs
Fixes #167, Fixes #130
> fix (UI): minor bugs

- README.md
- web/index.py
> docs: update README and home page help text.

- docs/user-guide/configuration.md
- docs/user-guide/llm-config.md
- misc/docker.env.template
- misc/secrets.toml.template
- mkdocs.yaml
- poetry.lock
- pyproject.toml
- source/docq/model_selection/main.py
- source/docq/services/__init__.py
- source/docq/services/credential_utils.py
- source/docq/services/google_drive.py
- source/docq/setup.py
- source/docq/support/llm.py
> feat: add support for Vertex AI Gemini Pro

- source/docq/manage_spaces.py
- tests/unit/docq/manage_documents_test.py
- tests/unit/docq/manage_organisations_test.py
- tests/unit/docq/manage_spaces_test.py
- tests/unit/docq/manage_users_test.py
Improve tests
Implements #170 
> tests: improve test coverage

- source/docq/services/credential_utils.py
- source/docq/services/google_drive.py
Update google drie service
Fixes #184 
> chore: Update google drive service to use credential json

- pyproject.toml
- web/api/chat_completion_handler.py
There were more incorrect imports, this time in the main code
> fix: broken imports

- pyproject.toml
- web/admin/index.py
- web/utils/layout.py
Allow org admin to edit spaces within the org
Fixes #205 
> 205 bug user isnt admin of their personal org

- web/api/chat_completion_handler.py
- web/api/utils.py
- web/index.py
> BUG: Fix api endpoint handlers.

- web/admin_spaces.py
- web/index.py
- web/utils/layout.py
> fix: Restore Admin_Spaces page.

- pyproject.toml
- web/index.py
- web/utils/handlers.py
- web/utils/layout.py
Update version and description in pyproject.toml
Update homepage unauth layout, content, and add Docq logo Update login form to show "subscribe" call to action if free sign up feature is disabled.
> chore: tweaks needed for Google app identity approval

- source/docq/manage_assistants.py
- web/ml_eng_tools/assistants.py
- web/utils/layout.py
- add initialisation with default assistants.
> fix: assistants list not rendering global assistants

- source/docq/data_source/support/web_extracting.py
- source/docq/data_source/web_scraper.py
- source/docq/domain.py
- web/utils/handlers.py
- web/utils/layout.py
> feat(webscraper): add support for a list of URLs

- pyproject.toml
- source/docq/model_selection/main.py
> feat: GPT4 Turbo 1106 preview service config + settings

- pyproject.toml
- source/docq/manage_assistants.py
- web/utils/layout.py
> fix: code chat history breaking chat `{` is present

- pyproject.toml
- source/docq/agents/main.py
- source/docq/data_source/support/web_extracting.py
- source/docq/data_source/web_scraper.py
- source/docq/domain.py
- source/docq/integrations/slack/manage_slack.py
- source/docq/integrations/slack/models.py
- source/docq/manage_assistants.py
- source/docq/manage_spaces.py
- source/docq/run_queries.py
- source/docq/support/llm.py
- tests/integration/backend_integration_test.py
- tests/unit/docq/support/llm_test.py
- web/admin/admin_integrations.py
- web/api/chat_completion_handler.py
- web/api/rag_completion_handler.py
- web/ml_eng_tools/rag.py
- web/utils/handlers.py
- web/utils/layout.py
> Slack improvements 3

- source/docq/manage_assistants.py
- source/docq/run_queries.py
- source/docq/support/llm.py
- source/docq/support/store.py
- web/api/base_handlers.py
- web/api/chat_completion_handler.py
- web/api/integration/utils.py
- web/api/models.py
- web/api/rag_completion_handler.py
- web/api/token_handler.py
- web/api/utils/auth_utils.py
- web/api/utils/constants.py
- web/api/utils/docq_utils.py
- web/utils/sessions.py
> fix: various web API improvements for the Chrome extension
